apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
  name: yorafa
spec:
  displayName: 彼岸-皓-Yorafa改
  author:
    name: Yorafa
    website: https://yorafa.com
  description: halo开发怎么那么麻烦
  logo: /themes/yorafa/assets/images/logo.png
  homepage: https://github.com/yorafa/halo-theme-higan-hz
  repo: https://github.com/yorafa/halo-theme-higan-hz.git
  issues: https://github.com/yorafa/halo-theme-higan-hz/issues
  settingName: yorafa-setting
  configMapName: yorafa-configmap
  version: 1.11.0
  requires: ">=2.1.0"
  license:
    - name: "MIT"
      url: "https://github.com/yorafa/halo-theme-higan-hz/blob/main/LICENSE"
