apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
  name: yorafa
  annotations:
    store.halo.run/app-id: app-homxf
spec:
  displayName: yorafa
  author:
    name: HowieHz
    website: https://howiehz.top
  description: 生死为此岸，涅槃为彼岸；有苦无乐为此岸，无苦无乐为彼岸...它代表着对一切美好的精神追求，也代表着生生不息的轮回亦如本主题分黑白两色，阴极阳至，向死而生。
  logo: /themes/howiehz-higan/assets/images/logo.png
  homepage: https://github.com/howiehz/halo-theme-higan-hz
  repo: https://github.com/howiehz/halo-theme-higan-hz.git
  issues: https://github.com/howiehz/halo-theme-higan-hz/issues
  settingName: yroafa-setting
  configMapName: yroafa-configmap
  version: 1.21.0
  requires: ">=2.1.0"
  license:
    - name: "MIT"
      url: "https://github.com/howiehz/halo-theme-higan-hz/blob/main/LICENSE"
